/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./*.html"],
    theme: {
        extend: {
            colors: {
                background: "#121412",
                primary: "#f2ca50",
                "secondary-fixed": "#ebddff",
                "primary-container": "#d4af37",
                "on-primary-fixed": "#241a00",
                "on-secondary-fixed-variant": "#4f3d72",
                "surface-container-low": "#1a1c1a",
                "surface-container-high": "#292a28",
                secondary: "#d2bcfa",
                "on-primary-container": "#554300",
                "on-surface": "#e3e3df",
                "on-tertiary-fixed-variant": "#47464a",
                error: "#ffb4ab",
                "surface-tint": "#e9c349",
                "inverse-primary": "#735c00",
                "primary-fixed": "#ffe088",
                "on-error-container": "#ffdad6",
                "surface-container-highest": "#333533",
                surface: "#121412",
                "on-primary": "#3c2f00",
                "secondary-fixed-dim": "#d2bcfa",
                "on-tertiary-container": "#454448",
                "surface-variant": "#333533",
                "on-tertiary": "#303033",
                "primary-fixed-dim": "#e9c349",
                "on-error": "#690005",
                "surface-dim": "#121412",
                "on-secondary-container": "#c1abe8",
                outline: "#99907c",
                "on-secondary": "#38265a",
                "inverse-on-surface": "#2f312e",
                "tertiary-fixed-dim": "#c8c5ca",
                "surface-bright": "#383a37",
                "on-tertiary-fixed": "#1b1b1e",
                "surface-container": "#1e201e",
                "on-background": "#e3e3df",
                "surface-container-lowest": "#0d0f0d",
                "tertiary-fixed": "#e4e1e6",
                "secondary-container": "#4f3d72",
                "on-primary-fixed-variant": "#574500",
                "inverse-surface": "#e3e3df",
                "on-secondary-fixed": "#231043",
                "outline-variant": "#4d4635",
                "on-surface-variant": "#d0c5af",
                "tertiary-container": "#b4b2b6",
                "error-container": "#93000a",
                tertiary: "#d0cdd2",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                gutter: "clamp(16px, 4vw, 32px)",
                "section-gap": "clamp(64px, 10vw, 128px)",
                unit: "8px",
                "margin-edge": "clamp(16px, 5vw, 64px)",
                "container-max": "1200px",
            },
            fontFamily: {
                "label-caps": ["Manrope", "sans-serif"],
                "body-lg": ["Manrope", "sans-serif"],
                "headline-xl": ["Noto Serif", "serif"],
                "headline-md": ["Noto Serif", "serif"],
                "headline-lg": ["Noto Serif", "serif"],
                "body-md": ["Manrope", "sans-serif"],
            },
            fontSize: {
                "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.2em", fontWeight: "700" }],
                "body-lg": ["clamp(16px, 2vw, 18px)", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
                "headline-xl": ["clamp(32px, 6vw, 48px)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
                "headline-md": ["clamp(20px, 4vw, 24px)", { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "500" }],
                "headline-lg": ["clamp(26px, 5vw, 32px)", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
                "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
            },
            maxWidth: {
                "container-max": "1200px",
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
};
